idf_component_register(
    SRCS
        "app_main.c"
        "cmd_time.c"
        "bsp/bsp_i2c.c"
        "bsp/bsp_axp2101.c"
        "bsp/bsp_xl9555.c"
        "bsp/bsp_display.c"
        "bsp/bsp_cst9217.c"
        "bsp/bsp_pcf85063.c"
        "bsp/bsp_sdcard.c"
        "ui/ui_clock.c"
        "ui/fonts/lv_font_montserrat_96.c"
        "screenshot.c"
        "power.c"
        "powerlog.c"
    INCLUDE_DIRS
        "."
        "bsp"
        "ui"
    REQUIRES
        console
        driver
        esp_driver_usb_serial_jtag
        esp_lcd
        esp_timer
        esp_hw_support
        esp_system
        fatfs
        freertos
        nvs_flash
        sdmmc
        esp_driver_sdspi
)
